### ISSUE TITLE
Support for more complex errors

### ISSUE THREAD

**Issue by kubaplas** [odradev/odra#111]
Currently, when trying to define the following error using execution_error! macro:
```rust
use odra::execution_error;
execution_error! {
        NoSuchMethod(String) => 1101,
}
```
We get a compilation error:
```rust
error: expected `=>`
  --> src/errors.rs:21:21
   |
21 |         NoSuchMethod(String) => 1101,
   |                     ^
```

It would be lovely to support such errors in the future.

**Comment by zie1ony** [comment]
Consider removing `execution_error` and use procedural macro. Could we use `thiserror`?

**Comment by zie1ony** [comment]
#232 covers that in new form.
