### ISSUE TITLE
CEP-78 implementation

### ISSUE THREAD

**Issue by ghost** [odradev/odra#197]
Is there any plan to provide example implementation of Casper standards, e.g. CEP-47 (base NFT) or CEP-78 (enhanced NFT)?

**Comment by zie1ony** [comment]
At the moment there is no plan of doing that. As far as I know CEP-47 is being decomission, and CEP-78 is still being explored (eg royality fies). On the other hand I'd like to see Odra implementation of CEP-78.

**Comment by zie1ony** [comment]
Planned for 1.0.0

**Comment by zie1ony** [comment]
Implemented in 1.0.0. There is also a tutorial: https://odra.dev/docs/next/tutorials/nft
