### ISSUE TITLE
OdraError

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#232]
Errors are numbers.

Users should be able to define their own errors. Possible code:
```rust
pub enum Erc20Error {
    InsufficientBalance = 1,
    InsufficientAllowance = 2
}

impl From<Erc20Error> for OdraError {
    fn from(error: Erc20Error) -> Self {
        OdraError::user(error as u32)
    }
}
```

Users should be able to easily test errors.
```rust
assert_eq!(erc20.try_transfer(bob, 10.into()), Err(Erc20Error::InsufficientBalance));
```

Error code spaces similar to existing impl.

**Comment by kpob** [comment]
Not sure if it can be done this way
`assert_eq!(erc20.try_transfer(bob, 10.into()), Err(Erc20Error::InsufficientBalance));`

A call would return an `OdraError` so to compare those errors we need to convert an OdraErrr into a custom error or vice versa.

The natural way is conversion into OdraError, but debugging becomes a bit harder.
If errors do not match we get, eg.
```
  left: `Err(ExecutionError(User(1)))`,
 right: `Err(ExecutionError(User(2)))`'
```

**Comment by zie1ony** [comment]
Next step is adding message to error and allow to read it on OdraVM for debugging.
