### ISSUE TITLE
Bring the `call_contract` error handling logic to `HostEnv`

### ISSUE THREAD

**Issue by kpob** [odradev/odra#250]
#248 changes the `HostContext::call_contract` return type from `Bytes` to `Result<Bytes, OdraError>` . Both implementations: `CasperHost` and `OdraVmHost` are almost the same. It could be unified in `HostEnv`.

At the moment, it is not a trivial change. The logic requires some `std` features, but `HostEnv` is placed in nostd `odra-core`.

One of the possible solutions is adding a new crate.

**Comment by zie1ony** [comment]
Not possible in wasm32 without std.
