### ISSUE TITLE
Make comparing events easier

### ISSUE THREAD

**Issue by kubaplas** [odradev/odra#251]
Now we recieve from last call result a vector of bytes representing events, so we need to convert events to bytes to compare them. Implement a macro with `into()` for Events that will convert them easily into Bytes.

**Comment by zie1ony** [comment]
I'd like the API allows for comparison of actually events, not `Bytes`.
Desired interface:
```rust


let call_result = env.last_call_result();
let event: Transfer = call_result.events.by_contract(&erc20).get(3); // panics if type missmissmatch with error: "Type missmatch, should be Transfer".
// Or event better
// let event: Transfer = call_result.events_by_contract(&erc20).get(3);

let expected = Transfer {
    from: Some(alice),
    to: Some(bob),
    amount: 30.into()
}
assert_eq!(event, expected);
```
Let's discuss the interface all together.
