### ISSUE TITLE
Contract metadata

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#257]

**Comment by zie1ony** [comment]
There is a working group that currently is defining Casper Contract Schema Standard (CCSS). Progress is tracked here: https://github.com/odradev/casper-contract-schema. After this is done, implement it in Odra.

**Comment by zie1ony** [comment]
I move it to `1.0.0` as it is not yet defined.

**Comment by kpob** [comment]
casper-contract-schema defines `Type`. A type can be Type::System for CLTypes or Type::Custom for user-defined types. @zie1ony,  what type is a Vector (Option, Result, Tuple) of custom type?

**Comment by kpob** [comment]
@zie1ony the dns example contains an enum definition as follows:
```rust
enum IP {
    IPv4(IPv4),                                            // single unnamed element,
    IPv4WithDescription(IPv4, String),                     // multiple unnamed elements,
    IPv6 { ip: IPv6 },                                     // single named element,
    IPv6WithDescription { ip: IPv6, description: String }, // multiple named elements,
}
```


and `EnumVariant` is

```rust
pub struct EnumVariant {
    pub name: String,
    pub description: Option<String>,
    pub discriminant: u8,
    pub ty: Type,
}
```

What is the type if a variant has no data?

```rust
enum IP {
    IPv4(IPv4),                                            // single unnamed element,
    IPv4WithDescription(IPv4, String),                     // multiple unnamed elements,
    IPv6 { ip: IPv6 },                                     // single named element,
    IPv6WithDescription { ip: IPv6, description: String }, // multiple named elements,
    Unknown // no associated data
}
```

I think the type should be `Option<Type>`

**Comment by kpob** [comment]
#382 #383 resolve the issue
