### ISSUE TITLE
Disable `wasm-env` and `livenet-env` from Codeconv

### ISSUE THREAD

**Issue by kubaplas** [odradev/odra#345]
I think you could disable `wasm-env` and `livenet-env` from Codeconv. You can do it by setting crates to test with `-p`.
```bash
cargo test -p odra -p odra-core ...
```

_Originally posted by @zie1ony in https://github.com/odradev/odra/pull/342#pullrequestreview-1861853815_

I think it will be better to try excluding it in `.codecov.yml` - Kuba

**Comment by zie1ony** [comment]
Go for it, if it is possible.
