### ISSUE TITLE
`NKVar` and `NKMapping`

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#399]
Introduce new kind of storage elements that operate based on the named keys. For variables it should be `NKVar` and for mappings `NKMapping`. `NK` from `Named Key`.

Named keys should be constructed at the installation step. If `Default` is not defined, the it should be empty bytes array and I can fail at deserialization step when not initialized.

They should be consider as sort of globals. Further checks that forbid or allow coexistence variables with the same names will be implemented later.

Building keys for mappings should mimic behavior from CasperLab's `cep18`.

Storing and loading named key based values should happen via `env` object, so it can be tested on OdraVM and loaded in livenet mode.

**Comment by kubaplas** [comment]
How about `NamedVar` and `NamedMapping`?

**Comment by kubaplas** [comment]
Started with #410
