### ISSUE TITLE
Unnecessary `deploy()` method.

### ISSUE THREAD

**Issue by zie1ony** [odradev/odra#50]
When the `#[deploy(init)]` method is specified don't generate `Module::deploy()` method. It's like this here: https://github.com/odradev/odra-template/blob/3259626c1a123a295ea56f5d6070b59bc3662917/src/flipper.rs#L47

Fix `odradev/odra-template` afterwards.

**Comment by kpob** [comment]
But why? Shouldn't we always have a default empty constructor?

**Comment by zie1ony** [comment]
Done.
